version: '3.7'

services:
  app:
    image: workspace/python:3.8.0-buster-python
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "2222:22"
    volumes:
      - .:/home/code/workspace
    networks:
      - python

networks:
  python:
