version: '3.7'

services:
  app:
    image: workspace/debian:10.2-golang
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "2222:22"
    volumes:
      - ./src:/home/code/workspace/src/app
    networks:
      - golang

networks:
  golang:
